// Generated by gencpp from file custom_msg/custom.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_CUSTOM_H
#define CUSTOM_MSG_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct custom_
{
  typedef custom_<ContainerAllocator> Type;

  custom_()
    : time(0.0)
    , data(0.0)  {
    }
  custom_(const ContainerAllocator& _alloc)
    : time(0.0)
    , data(0.0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::custom_msg::custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::custom_<ContainerAllocator> const> ConstPtr;

}; // struct custom_

typedef ::custom_msg::custom_<std::allocator<void> > custom;

typedef boost::shared_ptr< ::custom_msg::custom > customPtr;
typedef boost::shared_ptr< ::custom_msg::custom const> customConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::custom_<ContainerAllocator1> & lhs, const ::custom_msg::custom_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::custom_<ContainerAllocator1> & lhs, const ::custom_msg::custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32dad2e35d01ff0ba1fd46c34539c7a5";
  }

  static const char* value(const ::custom_msg::custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32dad2e35d01ff0bULL;
  static const uint64_t static_value2 = 0xa1fd46c34539c7a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/custom";
  }

  static const char* value(const ::custom_msg::custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"float64 data\n"
;
  }

  static const char* value(const ::custom_msg::custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::custom_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_CUSTOM_H
