// Generated by gencpp from file custom_msg/getDistanceRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_GETDISTANCEREQUEST_H
#define CUSTOM_MSG_MESSAGE_GETDISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct getDistanceRequest_
{
  typedef getDistanceRequest_<ContainerAllocator> Type;

  getDistanceRequest_()
    : locX(0.0)
    , locY(0.0)  {
    }
  getDistanceRequest_(const ContainerAllocator& _alloc)
    : locX(0.0)
    , locY(0.0)  {
  (void)_alloc;
    }



   typedef double _locX_type;
  _locX_type locX;

   typedef double _locY_type;
  _locY_type locY;





  typedef boost::shared_ptr< ::custom_msg::getDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::getDistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getDistanceRequest_

typedef ::custom_msg::getDistanceRequest_<std::allocator<void> > getDistanceRequest;

typedef boost::shared_ptr< ::custom_msg::getDistanceRequest > getDistanceRequestPtr;
typedef boost::shared_ptr< ::custom_msg::getDistanceRequest const> getDistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::getDistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::getDistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::getDistanceRequest_<ContainerAllocator1> & lhs, const ::custom_msg::getDistanceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.locX == rhs.locX &&
    lhs.locY == rhs.locY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::getDistanceRequest_<ContainerAllocator1> & lhs, const ::custom_msg::getDistanceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::getDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::getDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::getDistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd008fedca8f5e5953c4d8c76bbe1aed";
  }

  static const char* value(const ::custom_msg::getDistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd008fedca8f5e59ULL;
  static const uint64_t static_value2 = 0x53c4d8c76bbe1aedULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/getDistanceRequest";
  }

  static const char* value(const ::custom_msg::getDistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 locX\n"
"float64 locY\n"
;
  }

  static const char* value(const ::custom_msg::getDistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.locX);
      stream.next(m.locY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getDistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::getDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::getDistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "locX: ";
    Printer<double>::stream(s, indent + "  ", v.locX);
    s << indent << "locY: ";
    Printer<double>::stream(s, indent + "  ", v.locY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_GETDISTANCEREQUEST_H
