// Generated by gencpp from file beginner_tutorials/custom.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CUSTOM_H
#define BEGINNER_TUTORIALS_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>
#include <geometry_msgs/Pose2D.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct custom_
{
  typedef custom_<ContainerAllocator> Type;

  custom_()
    : robot_name()
    , data_time()
    , location()  {
    }
  custom_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , data_time(_alloc)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _robot_name_type;
  _robot_name_type robot_name;

   typedef  ::std_msgs::String_<ContainerAllocator>  _data_time_type;
  _data_time_type data_time;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::beginner_tutorials::custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::custom_<ContainerAllocator> const> ConstPtr;

}; // struct custom_

typedef ::beginner_tutorials::custom_<std::allocator<void> > custom;

typedef boost::shared_ptr< ::beginner_tutorials::custom > customPtr;
typedef boost::shared_ptr< ::beginner_tutorials::custom const> customConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::custom_<ContainerAllocator1> & lhs, const ::beginner_tutorials::custom_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name &&
    lhs.data_time == rhs.data_time &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::custom_<ContainerAllocator1> & lhs, const ::beginner_tutorials::custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::custom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d6c6b425f5ae28063ccf16e8002d35a";
  }

  static const char* value(const ::beginner_tutorials::custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d6c6b425f5ae280ULL;
  static const uint64_t static_value2 = 0x63ccf16e8002d35aULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/custom";
  }

  static const char* value(const ::beginner_tutorials::custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String robot_name\n"
"std_msgs/String data_time\n"
"\n"
"geometry_msgs/Pose2D location\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::beginner_tutorials::custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.data_time);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::custom_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_name);
    s << indent << "data_time: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.data_time);
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CUSTOM_H
